files:
  - source: /English/Mod/resource/MesaSecurity_**.txt
    translation: /%language%/Mod/resource/MesaSecurity_%language%.txt
  - source: English/Story/*.md
    translation: /%language%/Story/%original_file_name%
  - source: /English/Maps/Ideas.md
    translation: /%language%/Maps/%original_file_name%
